apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: registry-scanner
  namespace: kube-system
spec:
  chart: hello
  targetNamespace: default
  version: 0.1.19
  repo:  https://cloudecho.github.io/charts/
  helmVersion: v3
  failurePolicy: rollback