apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.selectorLabel }}
  name: {{ .Values.fullName}}
spec:
  ports:
    - port: {{ .Values.service.rpc }}
      name: rpc
      targetPort: {{ .Values.service.rpc }}
    - port: {{ .Values.service.gateway }}
      name: gateway
      targetPort: {{ .Values.service.gateway }}
  selector:
    app: {{ .Values.selectorLabel }}



