apiVersion: v1
kind: Service
metadata:
  name: alpha-ipfs-node-service
spec:
  type: ExternalName
  externalName: alpha.node.solenopsys.org
  ports:
    - port: {{ .Values.service.p2p }}
      name: p2p
      protocol: TCP


