apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.selectorLabel }}
  name: {{ .Values.fullName}}-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.p2p }}
      name: p2p
      targetPort: {{ .Values.service.p2p }}
    - port: {{ .Values.service.gateway }}
      name: gateway
      targetPort: {{ .Values.service.gateway }}
  selector:
    app: {{ .Values.selectorLabel }}



