apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.selectorLabel }}
  name: {{ .Values.fullName}}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.rpc }}
      name: rpc
      targetPort: {{ .Values.service.rpc }}
      nodePort: 30501
  selector:
    app: {{ .Values.selectorLabel }}



